[project]
name = "friendzone-detector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "john-l11", email = "john.e.lazaro@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "openai>=3.6.0",
    "requests>=2.34.2",
    "spotipy>=2.26.0",
]

[project.scripts]
friendzone-detector = "friendzone_detector:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
